apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurante-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurante-service
  template:
    metadata:
      labels:
        app: restaurante-service
    spec:
      containers:
        - name: restaurante-service
          image: rafaelloureioc/restaurante-service:latest
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: restaurante-service
spec:
  selector:
    app: restaurante-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
